#!/usr/bin/env python3
"""
import-adif.py — convert an ADIF (.adi) logbook export into data/log.yaml,
the format the site's logbook table reads.

Works with ADIF from QRZ, LoTW, N3FJP, WSJT-X, CQRLOG, etc. No dependencies.

Usage:
    python3 scripts/import-adif.py path/to/logbook.adi
    python3 scripts/import-adif.py logbook.adi -o data/log.yaml --limit 50
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime

# ADIF token: <TAG:len:type>value  OR  a value-less marker like <EOR> / <EOH>.
# The length group is optional so record/header markers are matched too.
FIELD_RE = re.compile(r"<([A-Za-z0-9_]+)(?::(\d+)(?::[^>]*)?)?>", re.IGNORECASE)


def parse_adif(text: str) -> list[dict]:
    """Yield one dict per QSO record. ADIF = <FIELD:len>value pairs, records
    separated by <EOR>. A header (if present) ends at <EOH>."""
    upper = text.upper()
    if "<EOH>" in upper:
        text = text[upper.index("<EOH>") + 5:]
    records: list[dict] = []
    fields: dict[str, str] = {}
    i = 0
    while i < len(text):
        m = FIELD_RE.search(text, i)
        if not m:
            break
        tag = m.group(1).upper()
        if tag == "EOR":  # end of record marker (no value)
            if fields:
                records.append(fields)
            fields = {}
            i = m.end()
            continue
        if m.group(2) is None:  # value-less field we don't care about
            i = m.end()
            continue
        length = int(m.group(2))
        val_start = m.end()
        value = text[val_start:val_start + length]
        i = val_start + length
        fields[tag] = value.strip()
    if fields:  # trailing record without a final <EOR>
        records.append(fields)
    return records


def to_yaml_str(s: str) -> str:
    s = (s or "").replace('"', "'")
    return f'"{s}"'


def fmt_date(adif_date: str) -> str:
    # ADIF QSO_DATE is YYYYMMDD
    if len(adif_date) == 8 and adif_date.isdigit():
        return f"{adif_date[0:4]}-{adif_date[4:6]}-{adif_date[6:8]}"
    return adif_date


def convert(records: list[dict]) -> list[dict]:
    out = []
    for r in records:
        qth = r.get("QTH") or r.get("STATE") or r.get("COUNTRY") or ""
        if r.get("SIG_INFO") or r.get("MY_SIG_INFO"):  # POTA/SOTA reference
            ref = r.get("SIG_INFO") or r.get("MY_SIG_INFO")
            qth = f"{ref}" + (f" ({qth})" if qth else "")
        out.append({
            "date": fmt_date(r.get("QSO_DATE", "")),
            "time": (r.get("TIME_ON", "") or "")[:4],
            "callsign": (r.get("CALL", "") or "").upper(),
            "band": (r.get("BAND", "") or "").lower(),
            "mode": (r.get("MODE", "") or "").upper(),
            "rst_s": r.get("RST_SENT", ""),
            "rst_r": r.get("RST_RCVD", ""),
            "qth": qth,
            "note": r.get("COMMENT", "") or r.get("NOTES", ""),
        })
    # newest first, by date+time
    out.sort(key=lambda q: (q["date"], q["time"]), reverse=True)
    return out


def write_yaml(qsos: list[dict], path: str) -> None:
    lines = [
        "# QSO log — generated by scripts/import-adif.py",
        f"# {len(qsos)} contacts, imported {datetime.now():%Y-%m-%d %H:%M}",
        "qsos:",
    ]
    for q in qsos:
        lines.append(f"  - date: {to_yaml_str(q['date'])}")
        for key in ("time", "callsign", "band", "mode",
                    "rst_s", "rst_r", "qth", "note"):
            lines.append(f"    {key}: {to_yaml_str(q[key])}")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main() -> int:
    p = argparse.ArgumentParser(description="ADIF -> data/log.yaml importer.")
    p.add_argument("adif", help="path to the .adi / .adif file")
    p.add_argument("-o", "--output", default="data/log.yaml",
                   help="destination YAML (default: data/log.yaml)")
    p.add_argument("--limit", type=int, default=0,
                   help="keep only the N most recent QSOs (0 = all)")
    args = p.parse_args()

    try:
        with open(args.adif, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    records = parse_adif(text)
    if not records:
        print("No QSO records found — is this a valid ADIF file?",
              file=sys.stderr)
        return 1

    qsos = convert(records)
    if args.limit > 0:
        qsos = qsos[:args.limit]
    write_yaml(qsos, args.output)
    print(f"Imported {len(qsos)} QSO(s) -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
